[package]
name = "rustql"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustql"
path = "src/lib.rs"

[[bin]]
name = "rustql"
path = "src/main.rs"

[dependencies]
atty = "0.2.14"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
